
###
GET  http://192.168.15.6:8080/api/health

###
POST http://192.168.15.6:8080/api/signup
Content-Type: application/json

{
  "name": "any_name",
  "cnpj": "any_cnpj",
  "email": "teste@teste.com",
  "telephone": "any_telephone",
  "city": "any_city",
  "district": "any_district",
  "street": "any_street",
  "fuelStationNumber": "any_fuelStationNumber",
  "cep": "any_cep",
  "flag": "any_flag",
  "isNetwork": "SIM",
  "networkName": "any_networkName",
  "password": "1",
  "passwordConfirmation": "1"
}

###

POST http://44.200.156.154:8080/api/signin
Content-Type: application/json

{
    "email": "s@s.com",
    "password": "1"
}

###
PATCH http://192.168.15.5:8080/api/reset-password
Content-Type: application/json

{
  "email": "5@teste.com"
}

