export default {
  grid: {
    container: '130%',
    gutter: '3.2%',
  },
  border: {
    radius: '0.4%',
  },
  font: {
    family:
      "Poppins, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
    light: 300,
    normal: 400,
    bold: 600,
    sizes: {
      xsmall: '1%',
      small: '1.4%',
      medium: '1.6%',
      large: '1.8%',
      xlarge: '2.0%',
      xxlarge: '2.8%',
    },
  },
  colors: {
    primary: '#1C1A29',
    secondary: '#2e9aff',
    mainBg: '#00227e',
    white: '#FAFAFA',
    black: '#030517',
    lightGray: '#EAEAEA',
    gray: '#8F8F8F',
    darkGray: '#2E2F42',
    border: '#2e9aff',
    bgInput: '#2F2C44',
    buttonDefault: '#867AD2',
    buttonDanger: '#D27A7A',
    buttonConfirm: '#7AD27D',
  },
  spacings: {
    xxsmall: '0.5%',
    xsmall: '1.6%',
    small: '2.4%',
    medium: '3.2%',
    large: '4.0%',
    xlarge: '4.8%',
    xxlarge: '5.6%',
  },
  layers: {
    base: 10,
    menu: 20,
    overlay: 30,
    modal: 40,
    alwaysOnTop: 50,
  },
  sizes: {
    small: '5%',
    medium: '10%',
    large: '20%',
    fullWidth: '100%',
  },
} as const;
